server:
  name: demo
  port: 9932
  env: local
  version: 1.0
  weight: 1
etcd:
  enable: true
  endpoints: 127.0.0.1:2379
mysql:
  default: root:root@tcp(127.0.0.1:3306)/nacos_devtest
nacos:
  ipaddr: 127.0.0.1:8848
  logdir: ./nacos
  cachedir: ./nacos
  dataid: demo
  group: demo
kafka:
  consumer:
    enable: true
    nodes:
      - 0.0.0.0:9093
    topic:
      - TestComposeTopic
    groupid: qqqq
  producer:
    enable: true
    nodes:
      - 0.0.0.0:9093
    topic: TestComposeTopic
logger:
  enablekafka: true
  path: ./logs
  name: vip-work
redis:
  enable: true
  addr: 0.0.0.0:6379
  db: 14